# 分支名
main:
  # 事件名
  push:
    # 要执行的任务
    - stages:
        - name: install-nodejs
          script: curl -fsSL https://nodejs.org/dist/v18.19.0/node-v18.19.0-linux-x64.tar.xz | tar -xJf - && export PATH=$PWD/node-v18.19.0-linux-x64/bin:$PATH && node -v && npm -v
        - name: install-dependencies
          script: npm install
        - name: build-project
          script: npm run build
        - name: echo-success
          script: echo "Build successful!"