# 分支名
main:
  # 事件名
  push:
    # 要执行的任务
    - stages:
        - name: install-nodejs
          script: apt-get update && apt-get install -y nodejs npm && node -v && npm -v
        - name: install-dependencies
          script: npm install
        - name: build-project
          script: npm run build
        - name: deploy-static
          script: echo "Deploying static website..." && ls -la dist/
        - name: echo-success
          script: echo "Build successful!"
