# 分支名
main:
  # 事件名
  push:
    # 要执行的任务
    - stages:
        - name: install-nodejs
          script: curl -fsSL https://fnm.vercel.app/install | bash && export PATH=$HOME/.local/share/fnm:$PATH && fnm use --install-if-missing 18 && node -v && npm -v
        - name: install-dependencies
          script: npm install
        - name: build-project
          script: npm run build
        - name: echo-success
          script: echo "Build successful!"